# Simple workflow that work on dispatch event
name: Simple Workflow
on: 
    workflow_dispatch:
    push:
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World"
      - name: multi-line command
        run: |
          echo "This is a multi-line command"
          echo "This is the second line"
  second_job:
    needs: first_job
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World"
      - name: multi-line command
        run: |
          echo "This is a multi-line command"
          echo "This is the second line"
  third_job:
    needs: first_job
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World"
      - name: multi-line command
        run: |
          echo "This is a multi-line command"
          echo "This is the second line"
  fourth_job:
    needs: [second_job, third_job]
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World"
      - name: multi-line command
        run: |
          echo "This is a multi-line command"
          echo "This is the second line"