#Gitub Action Workflow for Expression and Context
name: Expression and Context
on:
  push:
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Github Context
              run: |
                echo "Github Context"
                echo "{{toJSON(github)}}"


