#Gitub Action Workflow for Expression and Context
name: Expression and Context
on:
  push:
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Github Context
              run: |
                echo "Github Context"
                echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
                echo "GITHUB_SHA: $GITHUB_SHA"
                echo "GITHUB_REF: $GITHUB_REF"
                echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
                echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"
                echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
                echo "GITHUB_WORKFLOW: $GITHUB_WORKFLOW"
                echo "GITHUB_ACTION: $GITHUB_ACTION"
                echo "GITHUB_ACTOR: $GITHUB_ACTOR"
                echo "GITHUB_JOB: $GITHUB_JOB"
                echo "GITHUB_RUN_ID: $GITHUB_RUN_ID"
                echo "GITHUB_RUN_NUMBER: $GITHUB_RUN_NUMBER"
                echo "GITHUB_ACTION_REPOSITORY: $GITHUB_ACTION_REPOSITORY"
                echo "GITHUB_ACTION_REF: $GITHUB_ACTION_REF"


